name: evento

services:
  evento_1:
    build:
      context: .
    image: evento
    ports:
      - "8001:8000"
    restart: always
    depends_on:
      pg:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
      rmq:
        condition: service_healthy

  evento_2:
    build:
      context: .
    image: evento
    ports:
      - "8002:8000"
    restart: always
    depends_on:
      pg:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
      rmq:
        condition: service_healthy

  evento_3:
    build:
      context: .
    image: evento
    ports:
      - "8003:8000"
    restart: always
    depends_on:
      pg:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
      rmq:
        condition: service_healthy

  migration:
    build:
      context: .
    image: evento
    entrypoint: "./efbundle"
    depends_on:
      - pg

  rmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  pg:
    environment:
      - POSTGRES_DBNAME=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: "postgres:14"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
