version: "3.8"

services:
  evento:
    build:
      context: ./evento/
    ports:
      - "8000:8000"
    restart: always

  rmq:
    image: "rabbitmq:3.10-management"
    ports:
      - "5672:5672"
      - "15672:15672"
